version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:3.1.17
    container_name: aiohttp_resurface
    ports:
      - '7700:7700'
      - '7701:7701'


  postgres:
    image: postgres:10
    container_name: aiohttp_postgres
    volumes:
      - '/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock'
      - 'dbdata:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432

  aiohttp:
    image: test-aiohttp
    container_name: aiohttp
    ports:
      - '80:8080'
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  dbdata:
